### ISSUE TITLE
Quaternion Data Type (quat_t)

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/math3d#26]
# Description
Tracks the implementation of quaternions

## Rationale
This tracks the implementation of the `quaternion` Data Type (`quat_t`), which will be used in the codebase to represent orientations and implement rotations in an efficient way. Note we'll also have other Data Types to represent orientations|rotations (i.e. `Euler Angles`, and `Rotation Matrices`), but `quat_t` should be used internally for poses (i.e. `pose3d_t`)

## Tasks
- [x] Base API (`quat_t`)
- [x] Operations dispatching (`quat_t_impl`)
- [x] Operations `Scalar` implementation
- ~[ ] Operations `SSE` implementation~
- ~[ ] Operations `AVX` implementation~
- [x] `Examples` of its usage
- [x] `Python` bindings

**Comment by wpumacay** [comment]
Finished implementation in 79aa16ffa94ef03d3c6b02bbb815fe9aff4f0649 . We have only scalar implementations of the operations. `SIMD` support will be added as new operations require it.
