### ISSUE TITLE
Refactor unittests using custom generators

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/math3d#42]
# Description

The current unit tests for various _vector_ and _matrix_ types are using `catch2` generators that generate single scalars, and then we're combining them into the appropriate types we need. We should replace this with the custom generators we're using for the unit tests for `pose3d_t`.

```c++
// Generate 3 scalars using catch generators
auto x = GENERATE(take(num_samples, random(range_min, range_max)));
auto y = GENERATE(take(num_samples, random(range_min, range_max)));
auto z = GENERATE(take(num_samples, random(range_min, range_max)));

Vector3 v3_test(x, y, z);

// We should replace the code above with the following
auto v3_test = GENERATE(take(num_samples, ::math::random_vec3(range_min, range_max)));
```

# Tasks
- [x] Tests for `vec2_t`
- [x] Tests for `vec3_t`
- [x] Tests for `vec4_t`
- [x] Tests for `mat2_t`
- [x] Tests for `mat3_t`
- [x] Tests for `mat4_t`
- [x] Tests for `quat_t`
- [x] Tests for `euler_t`
- [x] Tests for `pose3d_t`
