### ISSUE TITLE
Documentation for Matrix types

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/math3d#48]
# Description

Should add `.rst` files for the docs for all **matrix** types. Use `sphinx` as well to combine with the manually generated docs.

## Tasks

- [ ] Add docs for `mat2_t`
- [ ] Add docs for `mat3_t`
- [ ] Add docs for `mat4_t`
